# Generated by Django 4.1.2 on 2022-10-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_crop_prevention_dry_crop_prevention_rainy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='prevention_dry',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='prevention_rainy',
        ),
        migrations.AddField(
            model_name='crop',
            name='prevention_dry_disease',
            field=models.TextField(default=1, verbose_name='Control & Prevention Disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='prevention_dry_pest',
            field=models.TextField(default=1, verbose_name='Control & Prevention Pest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='prevention_rainy_disease',
            field=models.TextField(default=1, verbose_name='Control & Prevention Disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='prevention_rainy_pest',
            field=models.TextField(default=1, verbose_name='Control & Prevention Pest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farms.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_planting',
            field=models.TextField(verbose_name='Crop Planting'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='risk_dry_disease',
            field=models.TextField(verbose_name='Risk Assessment Disease'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='risk_dry_pest',
            field=models.TextField(verbose_name='Risk Assessment Pest'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='risk_rainy_disease',
            field=models.TextField(verbose_name='Risk Assessment Disease'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='risk_rainy_pest',
            field=models.TextField(verbose_name='Risk Assessment Pest'),
        ),
    ]
